In [1]:
import numpy as np
arrays = [np.random.randn(3, 4) for _ in range(10)]

In [36]:
a = np.array([[1, 2], [4, 5], [7, 8]])
b = np.array([[11, 12], [14, 15], [17, 18]])
c = np.array([[21, 22], [24, 25], [27, 28]])
d = np.array([[31, 32], [34, 35], [37, 38]])
np.stack((a, b, c, d), axis=0)

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[11, 12],
        [14, 15],
        [17, 18]],

       [[21, 22],
        [24, 25],
        [27, 28]],

       [[31, 32],
        [34, 35],
        [37, 38]]])

In [37]:
np.stack((a, b, c, d), axis=1)

array([[[ 1,  2],
        [11, 12],
        [21, 22],
        [31, 32]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]],

       [[ 7,  8],
        [17, 18],
        [27, 28],
        [37, 38]]])

In [38]:
np.stack((a, b, c, d), axis=2)

array([[[ 1, 11, 21, 31],
        [ 2, 12, 22, 32]],

       [[ 4, 14, 24, 34],
        [ 5, 15, 25, 35]],

       [[ 7, 17, 27, 37],
        [ 8, 18, 28, 38]]])