# Week 1 demonstration
Yuchen

In [1]:
import numpy as np
np.__version__

'1.23.1'

In [2]:
a = 5
b = 6
c = "text"
d = 5.4
print(("a=%d b=%d c=%s d=%f")%(a,b,c,d))

a=5 b=6 c=text d=5.400000


In [3]:
prices = [1.4, 0.6, 0.4, 2.3]
print(prices)

[1.4, 0.6, 0.4, 2.3]


In [6]:
matrix = [[0.4, 0.5, 0.6],
         [0.7, 0.8, 0.9],
         [1.1, 1.2, 1.3]]
print(matrix)

[[0.4, 0.5, 0.6], [0.7, 0.8, 0.9], [1.1, 1.2, 1.3]]


In [7]:
mydict = {}
mydict["name"] = "Yuchen"
mydict["age"] = 30

print(mydict)

{'name': 'Yuchen', 'age': 30}


In [8]:
mydict = {"name":"Mark", "age":20}
print(mydict)

{'name': 'Mark', 'age': 20}


In [9]:
for i in mydict:
    print(i)
    print(mydict[i])

name
Mark
age
20


In [10]:
npmatrix = np.array(matrix)
print(npmatrix)

[[0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [1.1 1.2 1.3]]


In [11]:
max = np.max(npmatrix)
min = np.min(npmatrix)
print(max,min)

1.3 0.4


In [12]:
print(("Min = %.2f Max = %.2f")%(min, max))

Min = 0.40 Max = 1.30


In [13]:
rowsum = np.sum(npmatrix, axis=1)
print(rowsum)

[1.5 2.4 3.6]


In [15]:
colsum = np.sum(npmatrix, axis=0)
print(colsum)

[2.2 2.5 2.8]
